### ISSUE TITLE
Does not compile under Delphi x64

### ISSUE THREAD

**Issue by mknox74** [MHumm/DelphiEncryptionCompendium#15]
**Describe the bug**
Tried to compile my test application for x64 using Delphi 10.4.1 commandline compiler, and it failed with errors:

DECCiphers.pas(977) Error: E2010 Incompatible types: 'PBlowfish' and 'PByteArray'
DECCiphers.pas(1051) Error: E2010 Incompatible types: 'PBlowfish' and 'PByteArray'
DECCiphers.pas(2427) Error: E2010 Incompatible types: 'PUInt32Array' and 'PByteArray'
DECCiphers.pas(4726) Error: E2010 Incompatible types: 'PUInt32Array' and 'PByteArray'

**To Reproduce**
It can be reproduced straight away from your original sources package

1. Go to the Sources folder
2. Issue dcc32 -nsWinApi;System DEC60.dpr - compiles fine
3. Issue dcc64 -nsWinApi;System DEC60.dpr - fails with above errors

**Comment by MHumm** [comment]
I'll try to reproduce and fix as soon as time permits.
Which branch did you test? Development branch is newer.

**Comment by mknox74** [comment]
I've originally tested the "6.0 release" zip file.
Now that you've mentioned it, I have downloaded the latest master branch, and while compiling for x64 I'm getting errors:

DECUtil.pas(439) Error: E2003 Undeclared identifier: 'TUInt32Array'
DECUtil.pas(496) Error: E2003 Undeclared identifier: 'TUInt32Array'

**Comment by MHumm** [comment]
I fixed the x64 compilation issue now but when running the DUnit tests for x64 found that the following ciphers do not work correctly on x64 which work correctly on Win32: Blowfish, RC6 and Q128. Some first tests seem to indicate that it doesn't matter whether ASM or PUREPASCAL version is used.

**Comment by mknox74** [comment]
That's some bad news. Well, I have a master branch that I downloaded back on 24 May 2020, and it compiles fine under x64 AND Blowfish works correctly.

**Comment by MHumm** [comment]
Ok, thanks for the info about the old master branch working correctly. The current development branch should at least compile under x64 now. Can you confirm that? About the regressions in the cipher algorithms I need to investigate first, which will take some days as it's done in my spare time.

**Comment by mknox74** [comment]
Yes, I confirm, that the devel branch compiles under x64.
