### ISSUE TITLE
Broken ciphers on x64 platform

### ISSUE THREAD

**Issue by MHumm** [MHumm/DelphiEncryptionCompendium#16]
The following cipher algorithms do not properly pass their unit tests on x64 currently:

* Blowfish
* RC6
* Q128

They do pass their unit tests on x32 platform.
I haven't tested this on mobile platforms yet.

Any help in testing and fixing these issues is welcome.

**Comment by mknox74** [comment]
in DECCiphers.pas

procedure TCipher_Blowfish.DoEncode(Source, Dest: Pointer; Size: Integer);

change
  D := Pointer(FBuffer);
  P := Pointer(PByte(FBuffer) + SizeOf(Blowfish_Data)); // for Pointer Math

to
  D := Pointer(F**Additional**Buffer);
  P := Pointer(PByte(F**Additional**Buffer) + SizeOf(Blowfish_Data)); // for Pointer Math


Make the same change in
procedure TCipher_Blowfish.DoDecode(Source, Dest: Pointer; Size: Integer);


At some point you renamed FUser to FAdditionalBuffer, and you have maybe missed some replacements in the code. Given that, I dare to guess that the same applies to RC6 and Q128 encoders/decoders, but I haven't checked it.

**Comment by MHumm** [comment]
Thanks for this investigation! I'll try to implement that as soon as possible and maybe that points to the cause for the other algorithms. Reminds me of executing the unit tests before next release for x32 and x64 as well!

**Comment by MHumm** [comment]
Your investigation was quite helpful! I fixed all three of them and they're in development branch now.

**Comment by MHumm** [comment]
Your investigation was quite helpful! I fixed all three of them and they're in development branch now.
