### ISSUE TITLE
Haval hashes Rounds value is reset by Init call; Whirlpool rev2 missing; Tiger hash name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MHumm/DelphiEncryptionCompendium#2]
```
##1. Currently Haval hashes have "hardcoded" rounds value:
· THash_Haval128 = 128/3
· THash_Haval160 = 160/3
· THash_Haval192 = 192/4
· THash_Haval224 = 224/4
· THash_Haval256 = 256/5
~~ Would be helpful to allow to set Rounds value in constructor.


##2. Problem currently is that FCount (rounds) value is reset to "0" in 
"TDECHash.Init;" - called in CalcBuffer (CalcBinary), so even user created an 
object:

  Haval := THash_Haval256.Create;
  Haval.Rounds := 4;
  Haval.CalcBinary(Str, DECFmt.TFormat_HEXL);
  Haval.Free;

= would have no effect, because .SetRounds is called twice - 1st to "4", then 
2nd time by Init resets to "0", which will then results in default "5" value 
for 256 digest..


##3. Some of Hash functions have counterintuitive names:
· THash_Whirlpool  = is actually Whirlpool-0
· THash_Whirlpool1 = Whirlpool-T
· And Whirlpool/Whirlpool-2 = not implemented..

##4. Implemented "THash_Tiger" has is actually:
· Tiger (192/3)
~~ Would be helpful to change name / implement / allow to set Digest and 
Rounds..

For example:
· Tiger (128/3),  · Tiger (160/3),  · Tiger (192/3)
· Tiger (128/4),  · Tiger (160/4),  · Tiger (192/4)


##5. Would be useful to add "SHA-2 (224)" Hash


------------------------------------------------
## Current Haval workaround - manually calling all "Init, manual set, Calc" 
code:

program Project1;
{$AppType Console}
uses
  DECHash,
  DECFmt;

function Haval_Str(Str: string; DS: Integer; Rounds: Byte = 5): string;
var
  Haval: THashBaseHaval;
begin
  Result := '';

  case DS of
    128: Haval := THash_Haval128.Create;
    160: Haval := THash_Haval160.Create;
    192: Haval := THash_Haval192.Create;
    224: Haval := THash_Haval224.Create;
    256: Haval := THash_Haval256.Create;
  end;

  try
    Haval.Init; //Called by CalcBinary/CalcBuffer == Resets any customizations made..
    Haval.Rounds := Rounds; //override value.
    Haval.Calc(Str[1], Length(Str));
    Haval.Done;
    Result := Haval.DigestStr(DECFmt.TFormat_HEXL);
  finally
    Haval.Free;
  end;
end;

var
  d, r: Integer;
begin
  for r := 3 to 5 do
  begin
    d := 128;
    repeat
      Writeln( 'haval (', d, '/', r, '): ', Haval_Str('test', d, r) );
      inc(d, 32);
    until (d > 256);
    Writeln;
  end;
  Readln;
end.
------------------------------------------------
```

Original issue reported on code.google.com by `megamurm...@gmail.com` on 14 Nov 2012 at 5:20

**Comment by MHumm** [comment]
1. Some of the items are really worth to consider, maybe with aliased names
2. it would be helpful to hold to the good rule of one request per issue, as it would help us to process them individually and comment them individually etc.

**Comment by MHumm** [comment]
Hello,
at least in DEC V5.2 I cannot find your reported issue with resetting the rounds variable.  The actually used rounds variable is FRounds in the THashBaseHaval class which is only set in the setter of the Rounds property and in the initialization run before running any hash calculation this setter is being called as well. But it is being called with FRounds as parameter, so it will only change the number of rounds if somebody should have set FRounds to a value outside the allowed range of 3-5. So FRounds will never be 0, even after performing a hashing operation directly after class construction without setting the rounds property before, as the initialization will make sure it is within the range of 3-5 before performing the hash calculation.

Rereading your wording I see you refer to Init of the TDECHash base class. But this one only calls DoInit which is abstract there and thus overridden by the Haval Hash implementation which in that version ensures that rounds is between 3 and 5. So it will not be 0.

Or have I overlooked something?

**Comment by MHumm** [comment]
Status of the current development branch regarding your points:

##1: there is a Rounds property available now for setting this. It should not go into the constructor though because of compatibility with the other hash classes. Next commit will make it clearer, that the default for this Rounds property is 3.

##2: no longer the case

##3: needs to be checked

##4: There is a Rounds property available nowadays and I introduced Tiger192 as alias for Tiger now to make the situation clearer. Made a note on the internal to do list about Tiger 128 and 160, but that's nothing for the near future. Other things are more important right now.

##5: SHA-2 224 is already on the internal ToDo list, but nothing for the near future as well.

**Comment by MHumm** [comment]
3: has been checked and fixed in development branch! If you do not define the newly defined "dec 5.2 whirlpool compatible names" define names will be changed now and Whirlpool1 (sometimes named as 3.0), the variant of WhirlpoolT with optimized vectors has been implemented.

**Comment by MHumm** [comment]
Closed as it is mostly fixed. The remaining feature request is tracked as #40 now.
