### ISSUE TITLE
Error on compiling for Linux

### ISSUE THREAD

**Issue by arkadiusz-wolanski** [MHumm/DelphiEncryptionCompendium#22]
If I compile the Library for Linux as target Plattform an error occurs:

[DCC Fehler] DECHash.pas(325): E2100 Datentyp zu groß: 2 GB überschritten

Line 325 in DECHash:

TBABytes = array[0..MaxLongInt-1] of UInt8;

**Comment by MHumm** [comment]
I know this error and already fixed it in development branch.
Which branch did you test?
Instead of MaxLongint I put 65536 there, but even that might be higher than necessary.
But it was a quick initial fix for the issue. Issue might come from that code being written 
for Turbo Pascal initially.

**Comment by MHumm** [comment]
Be aware though, that we still have some crashes on Android at least. It seems to run properly on Win32.

**Comment by MHumm** [comment]
Did you retest this with the current development branch? Did it work for you so I can close the report?

**Comment by arkadiusz-wolanski** [comment]
@MHumm yes, it works.
Thank you!

**Comment by MHumm** [comment]
Close as fix was confirmed.
