### ISSUE TITLE
Are they really "Key deviation algorithms"?

### ISSUE THREAD

**Issue by Kromster80** [MHumm/DelphiEncryptionCompendium#25]
**Describe the bug**
Readme.md has the line "- Key **deviation** algorithms".

**Expected and actual behavior**
Should not it be "- Key **derivation** algorithms" instead?

**Comment by MHumm** [comment]
Derivation might be the better word choice indeed.
A fix for this has to wait until tomorrow though.
There are a few other things reported through a German forum needing fixes as well,
so if things work out as planned I'll try to fix all those tomorrow. That will most likely 
result in a 6.2.1 version.

**Comment by Kromster80** [comment]
Thanks for your reply!

According to Google and Wiki - that's the standard wording :-)
https://en.wikipedia.org/wiki/Key_derivation_function

// No hurry, just noted this and thought that was a typo

**Comment by MHumm** [comment]
Fixed.
