### ISSUE TITLE
Add Base32 for use with OTP

### ISSUE THREAD

**Issue by darianmiller** [MHumm/DelphiEncryptionCompendium#30]
I'd like to use DEC for creating One Time Passwords (OTP) such as Google Authenticator, but this requires Base32 encoding support
RFC 4226

**Comment by MHumm** [comment]
I had a short look at [https://datatracker.ietf.org/doc/html/rfc4226](https://datatracker.ietf.org/doc/html/rfc4226) but didn't see anything about Base32 in it. Looking into Wikipedia for Base32 I see rfc3548 and rfc3648 mentioned as standards for Base32.

If you like to contribute them I can guide you and of course you'd get credit in the list of contributors. In the limited spare time I have for DEC I'm currently working on two different issues, which will take further time. But I'd be happy to add your contribution!

**Comment by darianmiller** [comment]
base32 is used as industry standard way of dealing with Secret Keys with TOTP as in Google Authenticator.  I wrote my own version of it - covered it in a blog post: https://www.ideasawakened.com/post/base32-encoding-in-delphi-for-google-authenticator-replacement-app-part-one-in-series

**Comment by MHumm** [comment]
With interest I read your blog post.

Now since you were creating your own implementation, opposed to one of your
last mails where you wanted to use some generic library, I wonder why you
don't like to add that Base32 support to DEC?

With such additions (and then later on TOTP) we could make DEC "the one
shop stop" for Delphi open source cryptography.

**Comment by darianmiller** [comment]
Mainly as it spurred a bigger idea...write a blog series on Google Authenticator replacement.  I haven't wrote a technical blog post in a while and that sounded like a good series.  The code is open source so it could be added to DEC.

**Comment by MHumm** [comment]
Development branch contains an implementation of that one now. @darianmiller may contribute a TOTP implementation using that one now.
