### ISSUE TITLE
DEC 6.4 is not compatible to XE2 (and below) anymore

### ISSUE THREAD

**Issue by Gloegg** [MHumm/DelphiEncryptionCompendium#35]
The current release contains a few features not supported in XE2

**To Reproduce**
Open XE2
try to compile any 32bit project, that uses DEC (I haven't tried to compile 64bit)

**Details**

- In DECOptions.inc the compilerswitch {$LEGACYIFEND ON} is not available (was introduced in XE4)
- In DECCipherModesGCM.pas there are a couple places where a UInt64 variable is used in a for loop, which results in E2032 (For loop control variable must have ordinal type)
  - function TGCM.CalcGaloisHash(AuthenticatedData, Ciphertext : TBytes): T128;
  - procedure TGCM.DecodeGCM(Source, Dest: TBytes; Size: Integer);
  - procedure TGCM.EncodeGCM(Source, Dest: TBytes; Size: Integer);
- Also in DECCipherModesGCM.pas in the function TGCM.GetStandardAuthenticationTagBitLengths: TStandardBitLengths;
the assignment of an array to the result gives E2010 (Incompatible types - 'TStandardBitLengths' and 'Set')

**Comment by MHumm** [comment]
I'll have to check these. It might just take a few days as there are several things to do regarding bugfixes at the moment.

**Comment by MHumm** [comment]
Ok, I did some changes in the development branch. Can you please check those and give feedback?

**Comment by Gloegg** [comment]
It almost works. The constant array declaration is not yet working in XE2. I created a Pull Request for the last bit to have it work with XE2.
Thank you very much!
