### ISSUE TITLE
Idea: Mark broken ciphers as deprecated

### ISSUE THREAD

**Issue by Gloegg** [MHumm/DelphiEncryptionCompendium#36]
Maybe it's a good idea to mark ciphers, that shouldn't be used anymore as deprecated, so developers using these ciphers are warned when they use them.

**Comment by MHumm** [comment]
Maybe, but it has one consequence for me: I get deprecated warning all over in the unit tests. And the other issue is: who decides when a cipher is broken? Sometimes it's debatable or I sometimes cannot properly interpret the data telling how many iterations it takes to break it and if that's considered to be too week now...
The manual (did you read it? ;-) ) contains a list though...

**Comment by Gloegg** [comment]
Yeah ok, that is true. 
I had this idea, when I saw the list in the manual and askey myself if this info couldn't be brought directly to the source code :-)

**Comment by MHumm** [comment]
While the idea is not bad I wouldn't like to clutter compilation with deprecated warnings for those users which are forced for some reasons to use old algorithms. So I close this as won't do. In addition many of those contain warnings not only in the documentation but in the XMLDOC as well.
