### ISSUE TITLE
DECCipherInterface error

### ISSUE THREAD

**Issue by fastbike** [MHumm/DelphiEncryptionCompendium#45]
I have a project group that uses the DEC code base to replace some older DCrypt units.

There are two projects sharing the same code: one is compiled as a console EXE that runs a web server under localhost, the other is an ISAPI dll. So apart from the DPR file the code base is the same.

I can compile the EXE, but the DLL compilation fails with this error

`[dcc64 Error] DECCipherInterface.pas(746): E2134 Type '<void>' has no type info`

Commenting out the line at 486 in this unit
`    procedure Init(const Key; Size: Integer; const IVector; IVectorSize: Integer; IFiller: Byte = $FF); overload;`
allows compilation to succeed.

This method declaration contains an untyped parameter. Is this causing the failure ?
And if so why does it compile under the EXE but not the DLL?

**Comment by fastbike** [comment]
I've just found this SO discussion, not sure of the relevance but it mentions an interface with an untyped parameter
https://stackoverflow.com/questions/3458500/what-does-delphi-compiler-error-e2134-mean

**Comment by MHumm** [comment]
I'll have to read the SO post and check whether there are QP reports. Do I understand you correctly, that you do not use any DEC interfaces as interfaces but the compilation error comes from having these interface declarations "pulled in" when compiling as DLL?

**Comment by fastbike** [comment]
> 

Yes, it appears to be the case.  If I comment out the method in the interface with the untyped parameter it will compile.
I experimented as {M-} before the declaration of the interface ...
````
 {$M-}
  /// <summary>
  /// Common interface for all ciphers. Some ciphers may have additional
  /// methods/properties though!
  /// </summary>
  IDECCipher = Interface
    ['{73D70F28-95C0-4715-8C27-1AE6FBEE9698}']
...
````
... but this then caused another compilation error
`[dcc64 Error] DECHashAuthentication.pas(539): E2266 Only one of a set of overloaded methods can be published`
in the DECHashAuthentication.pas unit. Adding the "public" visibility specifier ahead of the offending method fixed that though
````
  public
    function CalcStream(const Stream: TStream; Size: Int64; Format: TDECFormatClass = nil;
                        const OnProgress:TDECProgressEvent = nil): RawByteString; overload;
````
As I noted non of this occurs in the EXE version ,just the DLL version. And I'm not using the interfaced versions of the ciphers.

**Comment by MHumm** [comment]
I'm in contact with somebody from EMBT. In order to have a look at the matter this person would like to have map files from you. Can you provide a map file from the compilation which fails and perhaps one from the exe where it succeds? If you do not want to post them in public you can send them per mail to me. My e-mail address is in the NOTICE.txt file.

Another question which came up was, whether it compiles in a regular DLL, so it would be restricted to ISAPIDLLs only? Can you perform a small check?

About your public section interface topic which seemed to have a positive effect: as I'm not aware of any side effects I'll try to find the time to ad public to all interface declarations.

**Comment by MHumm** [comment]
I'm not sure yet what to do with the "public" fixing the E2266 failure. Select the most likely candidate of each such overloaded method and add public?

**Comment by fastbike** [comment]
> I'm in contact with somebody from EMBT. In order to have a look at the matter this person would like to have map files from you. Can you provide a map file from the compilation which fails and perhaps one from the exe where it succeds? If you do not want to post them in public you can send them per mail to me. My e-mail address is in the NOTICE.txt file.
> 
> Another question which came up was, whether it compiles in a regular DLL, so it would be restricted to ISAPIDLLs only? Can you perform a small check?

OK, will do on Monday. My guess is that the ISAPI web units are doing something with the {M+} directive ?

**Comment by MHumm** [comment]
It looks like the map file does not contain what the EMBT engineer was loocking for. I'll try if I can get him to contact you directly, so I don't need to play the postman any longer. ;-)

**Comment by sglienke** [comment]
Check the compiler options of the DLL - if it has "Emit runtime type information" set - that is like globally turning on `{$M+}` for every type

**Comment by MHumm** [comment]
I just checked the compiler options of DEC itsself and there "Generate typeinfo" (I hope this is the right translation as I use the German IDE) is off, but reading this help topic seems to indicate that the interfaces provided by DEC might "pull" these in:
[https://docwiki.embarcadero.com/RADStudio/Sydney/de/Laufzeit-Typinformationen_(Delphi)](https://docwiki.embarcadero.com/RADStudio/Sydney/de/Laufzeit-Typinformationen_(Delphi))

**Comment by fastbike** [comment]
> Check the compiler options of the DLL - if it has "Emit runtime type information" set - that is like globally turning on `{$M+}` for every type

This was turned on, turning it off allows successful compilation.
However, what effect will it have on our use of:
- Eurekalog, and 
- the RTTI functions ?

**Comment by MHumm** [comment]
May I close this issue now, or shall I keep it open for you to report the consequences this has on the mentioned items?

**Comment by fastbike** [comment]
Keep it open and I will report back by end of week

**Comment by fastbike** [comment]
I've checked and it seems to have no effect on Eurekalog, or the (new) RTTI functions
