### ISSUE TITLE
Installing in Delphi 2010

### ISSUE THREAD

**Issue by AndyLudgate** [MHumm/DelphiEncryptionCompendium#61]
Not so sure this is a bug, but I want to use the compendium in D2010 and having trouble. 
I certainly don't want to use the installer project as I don't want it installed everywhere, but from what I could see, it basically just installs library paths, which I have done manually for a test project.
It has also been written for Delphi versions greater than D2010 since the uses clause for example is like:

uses
  System.SysUtils,
  System.Win.Registry,
  System.Classes;

which don't work for D2010 and changing these just leads me further down a rabbit hole.

Anyhow, just setting the path in the project options then gives me the compiler error: 

> [DCC Error] DECOptions.inc(98): E2029 $IFEND expected but $ENDIF found

> {$IFDEF FPC }
>   {$IF defined(CPUX86_64) or defined(CPUAMD64) or defined(CPUIA64) }
>     {$ifndef CPUX64}
>         {$define CPUX64}
>     {$endif}
>   {$else}{$if defined(CPU386) or defined(CPUI386) }
>       {$ifndef CPUX32}
>           {$define CPUX32}
>       {$endif}
>   {$ELSE}
>       {$IFNDEF ASSEMBLER }
>         {$DEFINE NO_ASM} (* default ON *)
>       {$ELSE}
>         {$IFDEF WINDOWS}
>           {.$DEFINE NO_ASM} (* default OFF *)
>         {$ELSE}
>           {$DEFINE NO_ASM} (* default ON *)
>         {$ENDIF}
>       {$ENDIF}
>   {$ENDIF}{$endif}     // line 98
> {$ELSE}
>   // Turn ASM off for FPC as we do not know enough about ASM support on FPC
>   {$DEFINE NO_ASM}
> {$ENDIF}
> 

FPC is not set so don't see why that line is even reached. 
Removing what looks like an extra {$endif} doesn't help.
Had some success replacing both the {$ENDIF}{$endif} with {$IFEND}{$ifend}, which required me to start removing the 'system.' prefix of a lot of the uses clauses in many other units, but that rabbit hole got to deep with other errors that I won't go into here.

If I set FPC then I just get an error in Indy10 with:

> [DCC Error] IdCompilerDefines.inc(528): E1030 Invalid compiler directive: 'MODE'

So the question I'm asking is, has anyone got this working with D2010 recently and can they tell me what I should do?

**Comment by MHumm** [comment]
As the main maintainer of this I have two suggestions:

1. Buy/get a current version of Delphi, D2010 is quite old already. 

2. The current version of DEC requires at least 10.1. But: you can look into the releases (right hand side on the main Github project page here) and pick an older release. V6.2.1 should definitively work for D2009+. Not sure for V6.3 and newer though.

These are the reasons why I'd say this is no bug and classified it as "won't fix". We have to go with the times. Even the 10.1 we have as minimum requirement nowadays is 6 years old already! So we have a longer support period compared to what EMBT has for the 3rd party stuff they sponsor, but based on new features comming up we now and then move the minimum requirement. I hope it is ok for you that I close this now.
