### ISSUE TITLE
Question about processing of last block of data using Done

### ISSUE THREAD

**Issue by danielmarschall** [MHumm/DelphiEncryptionCompendium#63]
In the examples we can see the following usage of encryption:

```
      // Encrypt
      Output := Cipher.EncodeBytes(Input);
      // clean up inside the cipher instance, which also removes the key from RAM
      Cipher.Done;

      // Decrypt
      Cipher.Init(RawByteString(StringOf(KeyKDF)), IV, 0);
      Output := Cipher.DecodeBytes(Output);
      // clean up inside the cipher instance, which also removes the key from RAM
      Cipher.Done;
```

The documentation of TDECCipher.Done says:

```
    ///   Properly finishes the cryptographic operation. It needs to be called
    ///   at the end of encrypting or decrypting data, otherwise the last block
    ///   or last byte of the data will not be properly processed.
```

(You probably also want to add the argument "removes the key from RAM" in that documentation)

I am confused about the argument "last block or last byte of data will not be properly processed". The `Done` method does not return data, so it looks like the "processing of the last block" is useless??

```
      Cipher.Init(RawByteString(StringOf(KeyKDF)), IV, 0);
      Output := Cipher.DecodeBytes(Output); // <-- output has been received here
      Cipher.Done; // <-- "processing" of the last block does not affect "Output"
```

So I wonder, am I missing something if I don't receive data from the "processing" of the last block? Thanks for clarification!

**Comment by MHumm** [comment]
I need to look at this. I think there are some algorithms where the data is only "complete" after calling Done as this in some cases not only removes keys etc. from memory but also finalizes some calculation. I have to chek the sample projects and change calling order, if that doesn't cause problems to better show how it should be used.

**Comment by danielmarschall** [comment]
If that is true that there are algorithms which require this, then we probably have a problem, since Done does not return data... the problem is that there are multiple ways to receive data, so we would need DoneToRawByteString, DoneToStream, DoneToBytes...

**Comment by MHumm** [comment]
Hm, ok, we have to investigate further. I might have mixed this up with the ciphers, as there sometimes special treatment of the last block is necessary.

**Comment by MHumm** [comment]
I had a look into the Done case now:

1. It calls DoDone internally, which has to be overwritten by the concrete implementations
2. It gets overwritten in TDECPasswordHash, but that's harmless. It calls the inherited version and it overwrites the salt value in RAM.
3. It gets overwritten here:

procedure THash_MD2.DoDone;
var
  Remain: Integer;
begin
  Remain := FBufferSize - FBufferIndex;
  FillChar(FBuffer[FBufferIndex], Remain, Remain);
  DoTransform(Pointer(FBuffer));
  Move(FDigest[48], FBuffer^, FBufferSize);
  DoTransform(Pointer(FBuffer));
end;

And as you can see it calls DoTransform on the buffer. And from MD2 quite a lot of the hash algorithms inherit (see class hierarchy tree in the documentation).

Tthe MD4 one also does quite a lot of things. It doesn't even call inherited as it replaces the MD2 one completely. Same for at least some SHA variants...

**Comment by danielmarschall** [comment]
I just want to make sure, we are talking about the **_ciphers_**, not the hashes, correct? :-)

**Comment by MHumm** [comment]
Ups! You're right of course! So this means for the hashes we established that Done must be called before accessing the generated hash value.

**Comment by danielmarschall** [comment]
I also checked the source code. In contrast to hashes, there is no "DoDone", and the virtual method "Done" is not overridden by any cipher, except in `TDECCipherModes.Done` which only does the GCM check.

I am very concerned that `TDECCipherModes.Done` calls `DoEncode(FFeedback, FBuffer, FBufferSize);`. This means that everything encrypted by DEC is incomplete. The information seems to be in `FBuffer`, but the developer cannot fetch this information using DecodeBytes(), DecodeStream(), etc.

It is probably a minor defect, because decryption does work... but on the other hand, interoperability might suffer if DEC's encrypted files have something missing at their file end. A decrypting tool written in another framework might have problems.





(I am sorry that I have so many topics. I know it is not good to work on multiple things in parallel, but when I work too long on one topic, like the Keccak one, then I need something else to refresh my mind)

**Comment by MHumm** [comment]
The question is: can we fetch the encrypted data after calling Done? If so we might just need to change the demo(s).

**Comment by danielmarschall** [comment]
With the current code, no.

Note that the someone noted that `FBuffer` does contain the "final data", but the comment reads like FBuffer is mostly a "pit hole" because something needs to be entered as parameter.

```
    /// <summary>
    ///   Some algorithms, mostly the cipher mode ones, need a temporary buffer
    ///   to work with. Some other methods like Done or Valid cipher need to pass
    ///   a buffer as parameter as that is ecpected by the called method.
    /// </summary>
    FBuffer: PUInt8Array;
```

I have a few solution ideas:

1. The not-so-good idea first:  `Done` could return the buffer as `TBytes`. Then the information is not lost. On the other hand, some people (like me) need to write this information to a stream, so it is a bit dirty to only output `TBytes`.

2. The better idea: We could change `DecodeRawByteString`, `DecodeStream`, ... in order to output the final buffer if the state is csDone.

Something like:

```
function TDECCipher.DecodeRawByteString(const Source: RawByteString; Format: TDECFormatClass): RawByteString;
begin
  if CipherState = csDone then
  begin
      Return FBuffer (as string, stream, bytes, etc.)
      Clear FBuffer (to avoid that Decode... is called multiple times after Done)
  end
  else
      Do the normal stuff and return it  (as string, stream, bytes, etc)
end;
```

Pro:
- We can receive the final buffer via string, bytes, stream, etc.
- Existing code would not be interrupted, because `DecodeRawByteString` should never have been called after `Done` anyways. It was illegal previously.

Contra:
- The definition (and human intuition) says that `Done` is the last thing you do, so calling `DecodeRawByteString` after it feels a bit odd...

**Comment by danielmarschall** [comment]
Oh, something else I noticed in the documentation:

```
  /// <para>
  ///   csDone : Processing is finished and Cipher.Done was called. Now new En/Decoding
  ///            can be started without calling .Init() before. csDone is basically
  ///            identical to csInitialized, except Cipher.Buffer holds the encrypted
  ///            last state of Cipher.Feedback, thus Cipher.Buffer can be used as C-MAC.
  /// </para>
```

Here, the author also noted that FBuffer contains the last cipher state.

And this is excatly what CalcMAC does:

```
function TDECCipher.CalcMAC(Format: TDECFormatClass): RawByteString;
begin
  Done;
  if FMode in [cmECBx] then
    raise EDECException.CreateRes(@sInvalidMACMode)
  else
    Result := ValidFormat(Format).Encode(FBuffer^, FBufferSize);
  { TODO : How to rewrite? EncodeBytes cannot be called directly like that }
end;
```

So, calling `CalcMAC` is the thing that needs to be done in order to receive the final data.

**Comment by MHumm** [comment]
Your last post means what exactly? We just need another overload for CalcMAC?

**Comment by danielmarschall** [comment]
Yes, if we have `CalcMACStream`, `CalcMACRawByteString`, `CalcMACBytes`, ... then it would work.

Though I would call it differently, because this last state CAN be used as MAC, but technically it is no MAC, but actually just the last block. So, I would call it `LastState` or `LastBlock`.  So `LastStateBytes`, `LastStateRawByteString`, `LastStateStream`, ...

Furthermore, I would do another change: While CalcMac throws an Exception for cipher mode ECB, the LastState/LastBlock method should just return nothing instead an Exception. Reason: An empty MAC is illegal, while an empty last block is okay.

What do you think?

**Comment by danielmarschall** [comment]
The usage would be:

```
      Cipher.Init(RawByteString(StringOf(KeyKDF)), IV, 0);
      Output := Cipher.DecodeRawByteString(Output);
      Cipher.Done;
      Output := Output + Cipher.LastStateRawByteString(Output);
```

**Comment by danielmarschall** [comment]
**_To conclude, my proposal is:_**


CalcMac (stays as follows):

- Throws an exception if cipher mode is ECB
- Returns FBuffer as RawByteString

LastStateBytes, LastStateRawByteString, LastStateStream:

- Throw an Exception if state is not csDone.  (this idea is new)
- Throws NO exception of cipher mode is ECB
- Returns FBuffer as bytes, stream, etc.

**Comment by MHumm** [comment]
It might be easier to have a phone call ;-)
If you send me an e-mail to the address in notices.txt you'll get my number... ;-)

**Comment by danielmarschall** [comment]
Update: We have found out that the contents of `FBuffer` is NOT a final encryption block. In fact, it is a MAC which is the **_encryption of the last feedback_** (even if we are in decipher-mode). Currently, there is no place in the code where `Done` will actually need to create a final block. So, when we call `Done`, we already have the full ciphertext and do not need to add anything to it. It is complete.

The only thing to do is to update the source code comments / documentation. I will send a pull-request this evening.

**Comment by MHumm** [comment]
I can now safely close this one.
